<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Plantilla\Module'                                => __DIR__ . '/Module.php',
    'Plantilla\Controller\PlantillaController'        => __DIR__ . '/src/Plantilla/Controller/PlantillaController.php',
    'Plantilla\Controller\TestController'             => __DIR__ . '/src/Plantilla/Controller/TestController.php',
    'Plantilla\DAO\Object\AbstractObject'             => __DIR__ . '/src/Plantilla/DAO/Object/AbstractObject.php',
    'Plantilla\DAO\Object\ColumnObject'               => __DIR__ . '/src/Plantilla/DAO/Object/ColumnObject.php',
    'Plantilla\DAO\Object\Db\ObjectMetadataInterface' => __DIR__ . '/src/Plantilla/DAO/Object/Db/ObjectMetadataInterface.php',
    'Plantilla\DAO\Object\Db\ObjectMetadataTrait'     => __DIR__ . '/src/Plantilla/DAO/Object/Db/ObjectMetadataTrait.php',
    'Plantilla\DAO\Object\ObjectDbInterface'          => __DIR__ . '/src/Plantilla/DAO/Object/ObjectDbInterface.php',
    'Plantilla\DAO\Object\ObjectDbTrait'              => __DIR__ . '/src/Plantilla/DAO/Object/ObjectDbTrait.php',
);
