<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
	'Plantilla\Module'                             => __DIR__ . '/Module.php',
    'Plantilla\Controller\PlantillaController'         => __DIR__ . '/src/Plantilla/Controller/PlantillaController.php',
    
);
