
	<label>Search:</label>
	<input type="text" id="txt-search"/><button type="button" id="btn-boton">boton</button>
	<div>
		<ul id="list">
			
		</ul>

	</div>


<script type="text/javascript">
	$('#btn-boton').click(function(){
		$.ajax({
			 type: "POST",
			 url: '<?php echo $this->url('test',array('action'=>'acltest'));?>',
			 data: {data:$('#txt-search').val()},
			 success: function(data,a,b){
				 if(data.success){
						console.log(data);
				 }				 
			 },
			 dataType: 'json'
		 });
	});

</script>
